# Generated by Django 4.0.4 on 2022-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='<function user_directory_path at 0x00000250C7C3D700>/% Y/% m/% d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
