# Generated by Django 4.0.4 on 2022-08-31 17:12

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feed_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='upload',
            field=models.ImageField(upload_to=api.models.user_directory_path),
        ),
    ]
